name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  developer-edition:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - name: Install dependencies
        run: |
          npm ci
          npm install --global @salesforce/cli
      - name: Authenticate Developer Edition and run test
        env:
          SFDX_AUTH_URL_DEVED: ${{ secrets.SFDX_AUTH_URL_DEVED }}
        run: |
          echo "${SFDX_AUTH_URL_DEVED}" | sf org login sfdx-url --set-default --alias mdapi-issues-deved --sfdx-url-stdin
          npm run test
  scratch-org:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - name: Install dependencies
        run: |
          npm ci
          npm install --global @salesforce/cli
      - name: Authenticate DevHub, create scratch org and run test
        env:
          SFDX_AUTH_URL_DEVHUB: ${{ secrets.SFDX_AUTH_URL_DEVHUB }}
        run: |
          echo "${SFDX_AUTH_URL_DEVHUB}" | sf org login sfdx-url --set-default-dev-hub --alias devhub --sfdx-url-stdin
          npm run develop
          npm run test
      - name: Delete scratch org
        if: always()
        run: |
          sf org delete scratch --no-prompt
